# Generated by Django 2.2 on 2019-09-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_groupdescription_groupdescription_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdescription',
            name='client_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payment.Client'),
            preserve_default=False,
        ),
    ]
