# Generated by Django 2.2 on 2019-09-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_groupdescription_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdescription',
            name='groupdescription_payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=264),
        ),
    ]
