# Generated by Django 2.2 on 2019-09-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_groupdescription_groupdescription_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_address',
            field=models.TextField(blank=True),
        ),
    ]
