# Generated by Django 2.2 on 2019-09-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_client_client_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupdescription',
            old_name='client_id',
            new_name='groupdescription_client_id',
        ),
    ]
