# Generated by Django 2.2.1 on 2019-09-18 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20190917_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdescription',
            name='groupdescription_date_time_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='airticketsquatation',
            name='service_type',
            field=models.CharField(default='Air Ticket Service', max_length=70),
        ),
        migrations.AlterField(
            model_name='entrancesquatation',
            name='service_type',
            field=models.CharField(default='Entrances Quatation Service', max_length=70),
        ),
        migrations.AlterField(
            model_name='hotelquatation',
            name='service_type',
            field=models.CharField(default='Hotel Quatation Service', max_length=70),
        ),
        migrations.AlterField(
            model_name='restaurantquatation',
            name='service_type',
            field=models.CharField(default='Restuarant Quatation Service', max_length=70),
        ),
        migrations.AlterField(
            model_name='sapsanquatation',
            name='service_type',
            field=models.CharField(default='SapSan Quatation Service', max_length=70),
        ),
        migrations.AlterField(
            model_name='visacostquatation',
            name='service_type',
            field=models.CharField(default='Visa Cost Service', max_length=70),
        ),
    ]
