# Generated by Django 2.2.1 on 2019-09-19 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20190918_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdescription',
            name='groupdescription_destination',
            field=models.CharField(default='', max_length=264),
        ),
        migrations.AddField(
            model_name='groupdescription',
            name='groupdescription_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='groupdescription',
            name='groupdescription_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
