# Generated by Django 2.2.1 on 2019-09-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20190919_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='airticketsquatation',
            name='airticket_arrival_at',
            field=models.CharField(default='', max_length=264),
        ),
        migrations.AddField(
            model_name='airticketsquatation',
            name='airticket_departure_from',
            field=models.CharField(default='', max_length=264),
        ),
    ]
