# Generated by Django 2.2.1 on 2019-09-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20190919_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airticketsquatation',
            name='airticket_GST',
            field=models.CharField(default='GST', max_length=264),
        ),
    ]
