# Generated by Django 2.2.1 on 2019-09-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20190919_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airticketsquatation',
            name='airticket_GST',
        ),
        migrations.AddField(
            model_name='airticketsquatation',
            name='airticket_type_of_GST',
            field=models.CharField(default='', max_length=264),
        ),
    ]
