# Generated by Django 2.2 on 2019-09-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20190919_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_number_of_passengers',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_quote_per_head',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_total_amount',
            field=models.IntegerField(blank=True),
        ),
    ]
