# Generated by Django 2.2.5 on 2019-09-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_auto_20190923_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('Air Ticket Service', 'Air Ticket Service'), ('Visa Cost Service', 'Visa Cost Service'), ('Hotel Quatation Service', 'Hotel Quatation Service'), ('Restuarant Quatation Service', 'Restuarant Quatation Service'), ('Entrances Quatation Service', 'Entrances Quatation Service'), ('SapSan Quatation Service', 'SapSan Quatation Service')], default='Air Ticket Service', max_length=264),
        ),
    ]
