# Generated by Django 2.2.1 on 2019-09-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airticketsquatation',
            name='airticket_booked_from',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
