# Generated by Django 2.2.1 on 2019-09-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_auto_20190926_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visacostquatation',
            name='visacost_visa_letter_cost',
            field=models.IntegerField(blank=True),
        ),
    ]
