# Generated by Django 2.2.1 on 2019-09-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_auto_20190926_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airticketsquatation',
            name='airticket_roe',
        ),
        migrations.RemoveField(
            model_name='airticketsquatation',
            name='airticket_type_of_GST',
        ),
        migrations.RemoveField(
            model_name='hotelquatation',
            name='hotelquatation_CGST',
        ),
        migrations.RemoveField(
            model_name='visacostquatation',
            name='visacost_CGST',
        ),
        migrations.RemoveField(
            model_name='visacostquatation',
            name='visacost_roe',
        ),
        migrations.RemoveField(
            model_name='visacostquatation',
            name='visacost_visa_letter_cost',
        ),
        migrations.AddField(
            model_name='service',
            name='service_gst',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='service_payment_method',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='service_roe',
            field=models.CharField(blank=True, default='', max_length=264),
        ),
    ]
