# Generated by Django 2.2.1 on 2019-10-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0024_auto_20190927_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'admin'), (1, 'super_admin')], default=2),
        ),
    ]
