# Generated by Django 2.2.1 on 2019-10-04 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0026_auto_20191002_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='office_location',
            field=models.CharField(choices=[('MUMBAI', 'MUMBAI'), ('DELHI', 'DELHI'), ('RUSSIA', 'RUSSIA')], default='MUMBAI', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_short_name',
            field=models.CharField(default='ST', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrancesquatation',
            name='entrancesquatation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='groupdescription',
            name='groupdescription_vtrefNo_short',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guide',
            name='guide_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hotelquatation',
            name='hotelquatation_check_in_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hotelquatation',
            name='hotelquatation_check_out_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='restaurantquatation',
            name='restaurantquatation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sapsanquatation',
            name='sapsanquatation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visacostquatation',
            name='visacost_date_and_time_of_generation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupdescription',
            name='groupdescription_vtrefNo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_gst',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_quote_per_head',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_roe',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_total_amount',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
