# Generated by Django 2.2.1 on 2019-10-07 05:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_auto_20191004_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.Service')),
                ('service_type', models.CharField(default='Transport Service', max_length=920)),
                ('transport_type_of_vehicle', models.CharField(default='', max_length=920)),
                ('transport_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transport',
            },
            bases=('payment.service',),
        ),
        migrations.AddField(
            model_name='client',
            name='client_email',
            field=models.CharField(default='', max_length=920),
        ),
        migrations.AddField(
            model_name='client',
            name='client_telephone',
            field=models.CharField(default='', max_length=920),
        ),
        migrations.AddField(
            model_name='groupdescription',
            name='groupdescription_remark',
            field=models.CharField(default='', max_length=920),
        ),
        migrations.AddField(
            model_name='groupdescription',
            name='groupdescription_roe',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_email',
            field=models.CharField(default='', max_length=920),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_mobile',
            field=models.CharField(default='', max_length=920),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_remark',
            field=models.CharField(default='', max_length=920),
        ),
        migrations.AlterField(
            model_name='airticketsquatation',
            name='airticket_airline_name',
            field=models.CharField(max_length=920),
        ),
        migrations.AlterField(
            model_name='airticketsquatation',
            name='airticket_arrival_at',
            field=models.CharField(default='', max_length=920),
        ),
        migrations.AlterField(
            model_name='airticketsquatation',
            name='airticket_booked_from',
            field=models.CharField(blank=True, max_length=920),
        ),
        migrations.AlterField(
            model_name='airticketsquatation',
            name='airticket_departure_from',
            field=models.CharField(default='', max_length=920),
        ),
        migrations.AlterField(
            model_name='airticketsquatation',
            name='service_type',
            field=models.CharField(default='Air Ticket Service', max_length=920),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_address',
            field=models.CharField(max_length=920),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=920),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='office_location',
            field=models.CharField(choices=[('MUMBAI', 'MUMBAI'), ('DELHI', 'DELHI'), ('RUSSIA', 'RUSSIA')], default='MUMBAI', max_length=920),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_short_name',
            field=models.CharField(max_length=920),
        ),
        migrations.AlterField(
            model_name='entrancesquatation',
            name='entrancesquatation_name',
            field=models.CharField(max_length=920),
        ),
        migrations.AlterField(
            model_name='entrancesquatation',
            name='service_type',
            field=models.CharField(default='Entrances Quatation Service', max_length=920),
        ),
        migrations.AlterField(
            model_name='groupdescription',
            name='groupdescription_client_Name',
            field=models.CharField(max_length=920),
        ),
        migrations.AlterField(
            model_name='groupdescription',
            name='groupdescription_client_handle_person',
            field=models.CharField(max_length=920),
        ),
        migrations.AlterField(
            model_name='groupdescription',
            name='groupdescription_destination',
            field=models.CharField(default='', max_length=920),
        ),
        migrations.AlterField(
            model_name='groupdescription',
            name='groupdescription_payment_method',
            field=models.CharField(max_length=920),
        ),
        migrations.AlterField(
            model_name='groupdescription',
            name='groupdescription_payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=920),
        ),
        migrations.AlterField(
            model_name='groupdescription',
            name='groupdescription_volshebny_handle_person',
            field=models.CharField(max_length=920),
        ),
        migrations.AlterField(
            model_name='groupdescription',
            name='groupdescription_vtrefNo',
            field=models.CharField(max_length=920),
        ),
        migrations.AlterField(
            model_name='guide',
            name='Guide_Destination',
            field=models.CharField(max_length=920),
        ),
        migrations.AlterField(
            model_name='guide',
            name='Guide_Name',
            field=models.CharField(max_length=920),
        ),
        migrations.AlterField(
            model_name='guide',
            name='service_type',
            field=models.CharField(default='Guide Service', max_length=920),
        ),
        migrations.AlterField(
            model_name='hotelquatation',
            name='hotelquatation_breakfast_provided',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=920),
        ),
        migrations.AlterField(
            model_name='hotelquatation',
            name='hotelquatation_hotel_name',
            field=models.CharField(max_length=920),
        ),
        migrations.AlterField(
            model_name='hotelquatation',
            name='hotelquatation_type_of_room',
            field=models.CharField(choices=[('Single Occupancy', 'Single Occupancy'), ('Double Occupancy', 'Double Occupancy'), ('Triple Occupancy', 'Triple Occupancy')], default='Single Occupancy', max_length=920),
        ),
        migrations.AlterField(
            model_name='hotelquatation',
            name='service_type',
            field=models.CharField(default='Hotel Quatation Service', max_length=920),
        ),
        migrations.AlterField(
            model_name='restaurantquatation',
            name='restaurantquatation_For',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Lunch', max_length=920),
        ),
        migrations.AlterField(
            model_name='restaurantquatation',
            name='restaurantquatation_resturant_name',
            field=models.CharField(max_length=920),
        ),
        migrations.AlterField(
            model_name='restaurantquatation',
            name='service_type',
            field=models.CharField(default='Restuarant Quatation Service', max_length=920),
        ),
        migrations.AlterField(
            model_name='sapsanquatation',
            name='sapsanquatation_From_Station',
            field=models.CharField(max_length=920),
        ),
        migrations.AlterField(
            model_name='sapsanquatation',
            name='sapsanquatation_To_Station',
            field=models.CharField(max_length=920),
        ),
        migrations.AlterField(
            model_name='sapsanquatation',
            name='service_type',
            field=models.CharField(default='SapSan Quatation Service', max_length=920),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_number_of_passengers',
            field=models.CharField(blank=True, max_length=920),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_payment_method',
            field=models.CharField(default='', max_length=920),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_vendor_payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=920),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_address',
            field=models.CharField(max_length=920),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(max_length=920),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('Air Ticket Service', 'Air Ticket Service'), ('Visa Cost Service', 'Visa Cost Service'), ('Hotel Quatation Service', 'Hotel Quatation Service'), ('Restuarant Quatation Service', 'Restuarant Quatation Service'), ('Entrances Quatation Service', 'Entrances Quatation Service'), ('SapSan Quatation Service', 'SapSan Quatation Service'), ('Guide Service', 'Guide Service')], default='Air Ticket Service', max_length=920),
        ),
        migrations.AlterField(
            model_name='visacostquatation',
            name='service_type',
            field=models.CharField(default='Visa Cost Service', max_length=920),
        ),
        migrations.AlterField(
            model_name='visacostquatation',
            name='visacost_time_period',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent')], default='Normal', max_length=920),
        ),
        migrations.AlterField(
            model_name='visacostquatation',
            name='visacost_type_of_Visa',
            field=models.CharField(choices=[('Tourist single', 'Tourist single'), ('Tourist Double', 'Tourist Double'), ('Business', 'Business')], default='Tourist single', max_length=920),
        ),
    ]
