# Generated by Django 2.2.1 on 2019-10-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_auto_20191007_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdescription',
            name='group_description_service_calculation_type',
            field=models.CharField(choices=[('INCLUSIVE', 'INCLUSIVE'), ('EXCLUSIVE', 'EXCLUSIVE')], default='EXCLUSIVE', max_length=920),
        ),
    ]
