# Generated by Django 2.2.1 on 2019-10-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0032_auto_20191010_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visacostquatation',
            name='visacost_service_cost',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
