# Generated by Django 2.2.1 on 2019-10-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0034_auto_20191014_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdescription',
            name='groupdescription_remark',
            field=models.CharField(blank=True, max_length=920),
        ),
    ]
