# Generated by Django 2.2.7 on 2019-11-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0042_visitingcardcompanydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitingcardcompanydata',
            name='visitingcardcompanydata_company_address1',
            field=models.TextField(max_length=920),
        ),
        migrations.AlterField(
            model_name='visitingcardcompanydata',
            name='visitingcardcompanydata_company_address2',
            field=models.TextField(blank=True, max_length=920),
        ),
    ]
