# Generated by Django 2.2.7 on 2019-11-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0043_auto_20191125_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitingcardcompanydata',
            name='visitingcardcompanydata_convert_to_client',
            field=models.BooleanField(default=False),
        ),
    ]
