# Generated by Django 2.2.7 on 2019-11-29 11:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0045_auto_20191129_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chefservice',
            fields=[
                ('service_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.Service')),
                ('service_type', models.CharField(default='Chef Service', max_length=920)),
                ('chefservice_chef_name', models.CharField(default='', max_length=920)),
                ('chefservice_chef_destination', models.CharField(blank=True, max_length=920)),
                ('chefservice_no_of_days', models.IntegerField()),
                ('chefservice_quote_per_day', models.FloatField(blank=True)),
                ('chefservice_chef_roe', models.FloatField(blank=True)),
                ('chefservice_gst_percentage', models.FloatField(blank=True)),
                ('chefservice_total_amount', models.FloatField(blank=True, default=0.0)),
                ('chefservice_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Chefservice',
                'verbose_name_plural': 'Chef Service',
            },
            bases=('payment.service',),
        ),
    ]
