# Generated by Django 2.2.7 on 2019-11-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0047_remove_chefservice_chefservice_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefservice',
            name='chefservice_gst_percentage',
        ),
    ]
