# Generated by Django 2.2.7 on 2019-11-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0048_remove_chefservice_chefservice_gst_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefservice',
            name='chefservice_chef_roe',
        ),
    ]
