# Generated by Django 2.2.7 on 2019-11-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0049_remove_chefservice_chefservice_chef_roe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefservice',
            name='chefservice_quote_per_day',
        ),
    ]
