# Generated by Django 2.2.7 on 2019-11-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0050_remove_chefservice_chefservice_quote_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefservice',
            name='chefservice_no_of_days',
        ),
    ]
