# Generated by Django 2.2.7 on 2019-12-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0051_remove_chefservice_chefservice_no_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdescription',
            name='groupdescription_number_of_passengers_paid',
            field=models.IntegerField(blank=True),
        ),
    ]
