# Generated by Django 2.2.7 on 2019-12-02 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0052_auto_20191202_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdescription',
            name='groupdescription_confirmation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
