# Generated by Django 2.2.7 on 2019-12-02 05:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0053_auto_20191202_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdescription',
            name='groupdescription_booking_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='groupdescription',
            name='groupdescription_confirmation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
