# Generated by Django 2.2.7 on 2019-12-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0054_auto_20191202_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdescription',
            name='groupdescription_number_of_passengers_paid',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
