# Generated by Django 2.2.7 on 2019-12-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0055_auto_20191202_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdescription',
            name='groupdescription_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='groupdescription',
            name='groupdescription_start_date',
            field=models.DateTimeField(),
        ),
    ]
