# Generated by Django 2.2.7 on 2019-12-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0056_auto_20191202_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='allservices',
            name='allservices_chef',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('Air Ticket Service', 'Air Ticket Service'), ('Visa Cost Service', 'Visa Cost Service'), ('Hotel Quatation Service', 'Hotel Quatation Service'), ('Restuarant Quatation Service', 'Restuarant Quatation Service'), ('Entrances Quatation Service', 'Entrances Quatation Service'), ('SapSan Quatation Service', 'SapSan Quatation Service'), ('Guide Service', 'Guide Service'), ('Transport Service', 'Transport Service'), ('All Services', 'All Services'), ('Chef Service', 'Chef Service')], default='Air Ticket Service', max_length=920),
        ),
    ]
