# Generated by Django 2.2.1 on 2019-12-23 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitingCardCompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitingcardcompanydata_company_name', models.CharField(max_length=920)),
                ('visitingcardcompanydata_agent_name', models.CharField(max_length=920)),
                ('visitingcardcompanydata_agent_designation', models.CharField(blank=True, max_length=920)),
                ('visitingcardcompanydata_company_address1', models.TextField(max_length=920)),
                ('visitingcardcompanydata_company_address2', models.TextField(blank=True, max_length=920)),
                ('visitingcardcompanydata_tel_number1', models.CharField(max_length=920)),
                ('visitingcardcompanydata_tel_number2', models.CharField(blank=True, max_length=920)),
                ('visitingcardcompanydata_mobile_number1', models.CharField(max_length=920)),
                ('visitingcardcompanydata_mobile_number2', models.CharField(blank=True, max_length=920)),
                ('visitingcardcompanydata_email_id1', models.CharField(max_length=920)),
                ('visitingcardcompanydata_email_id2', models.CharField(blank=True, max_length=920)),
                ('visitingcardcompanydata_company_website', models.CharField(blank=True, max_length=920)),
                ('visitingcardcompanydata_date_of_entry', models.DateTimeField(default=django.utils.timezone.now)),
                ('visitingcardcompanydata_convert_to_client', models.BooleanField(default=False)),
                ('visitingcardcompanydata_importance', models.CharField(choices=[('HIGH', 1), ('MEDIUM', 2), ('LOW', 3)], default=4, max_length=920)),
                ('visitingcardcompanydata_welcome_sms_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Compony Data',
                'verbose_name_plural': 'VisitingCardCompanyData',
            },
        ),
    ]
