# Generated by Django 2.2.1 on 2020-01-03 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visiting_card_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SMS_Subject', models.CharField(max_length=100)),
                ('SMS_Message', models.CharField(max_length=150)),
                ('SMS_Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'SMS Templates',
                'verbose_name_plural': 'SMS Template',
            },
        ),
    ]
