# Generated by Django 2.2.1 on 2020-01-03 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visiting_card_data', '0002_smsmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_Subject', models.CharField(max_length=900)),
                ('Email_Message', models.CharField(max_length=1600)),
                ('Email_Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Email Templates',
                'verbose_name_plural': 'Email Template',
            },
        ),
    ]
